language: php
php:
  - 7.0
  - 7.1
  - 7.2
sudo: false
services:
  - mysql
before_install:
  - phpenv config-rm xdebug.ini
  - mysql -e 'create database fusio;'
install:
  - composer install
  - php bin/fusio install
before_script:
  - php bin/fusio deploy
script:
  - vendor/bin/phpunit
