# If true the status of a new app is PENDING so that an administrator has to 
# manually activate the app
app_approval: 0
# The max amount of apps a consumer can register
app_consumer: 16
# If a user registers through the consumer API the following scopes are assigned
scopes_default: "authorization,consumer"
# Subject of the activation mail
mail_register_subject: "Fusio registration"
# Body of the activation mail
mail_register_body: "Hello {name},

  you have successful registered at Fusio.
  To activate you account please visit the following url:
  ${env.FUSIO_URL}\/developer\/activate?token={token}"
# Email address which is used in the "From" header
mail_sender: ""
# Facebook app secret
provider_facebook_secret: "${env.PROVIDER_FACEBOOK_SECRET}"
# Google app secret
provider_google_secret: "${env.PROVIDER_GOOGLE_SECRET}"
# GitHub app secret
provider_github_secret: "${env.PROVIDER_GITHUB_SECRET}"
# ReCaptcha secret
recaptcha_secret: "${env.RECAPTCHA_SECRET}"
# If set each API response contains a Access-Control-Allow-Origin header with 
# the provided value
cors_allow_origin: "*"
